require("myprograms")
require("keybindings")
require("monitors")
require("appearance")

-- Autostart certain apps
hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
	hl.exec_cmd("waybar")
	hl.exec_cmd("/usr/bin/dunst")
	hl.exec_cmd("/home/levi/Applications/Sunshine_2026.914.233613_x86_64.AppImage")
	hl.exec_cmd("/home/levi/Applications/MoonDeckBuddy-1.10.0-x86_64.AppImage")
	--hl.exec_cmd("steam")
	hl.dsp.exec_raw("wl-paste --type text --watch cliphist store")
	hl.dsp.exec_raw("wl-paste --type image --watch cliphist store")
	hl.dsp.exec_raw("sudo systemctl start tailscaled")
	hl.dsp.exec_raw("sudo tailscale up")
	hl.exec_cmd("hyprctl setcursor Banana 32")
	hl.exec_cmd("linux-wallpaperengine --screen-root DP-3 --set-property interloper=0 --silent 2984500160")
	hl.exec_cmd("linux-wallpaperengine --screen-root HDMI-A-1 --set-property interloper=0 --silent 2984500160")
	hl.exec_cmd("thunar --daemon")
end)
